Restaurant_Management/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurant_Management.Controllers
{
    public class CommonController : Controller
    {
        Restaurant_ManagementEntities1 ctx = new Restaurant_ManagementEntities1();
        // GET: Common
        public ActionResult Index()
        {
            return View();
        }

        //public PartialViewResult getNav()
        //{
        //    return PartialView("_NavHeader", ctx.tblNavHeaders.Where(w => w.IsHeader == true).ToList());
        //}

        //public PartialViewResult getFooter()
        //{
        //    return PartialView("_Footer", ctx.tblNavHeaders.Where(w => w.IsHeader == false).ToList());
        //}

    }
}

Restaurant_Management/Views/Shared/_Footer.cshtml
@*@model IEnumerable<tblMenuHeader>*@

<div class="container-fluid bg-black text-white">
    <div class="row">
        <div class="col-3">
            <ul type="none">
                @foreach (var item in Model.Take(5).ToList())
                {
                    <a href="@Url.Action(item.ActionName, item.ControllerName)">
                    <li>@item.Title</li>
                    </a>
                }
            </ul>
        </div>
        <div class="col-3">
            <ul type="none">
                @foreach (var item in Model.Skip(5).Take(5).ToList())
                {
                    <a href="@Url.Action(item.ActionName, item.ControllerName)">
                    <li>@item.Title</li>
                    </a>
                }
            </ul>
        </div>
        <div class="col-3">
            <ul type="none">
                @foreach (var item in Model.Skip(10).Take(5).ToList())
                {
                    <a href="@Url.Action(item.ActionName, item.ControllerName)">
                    <li>@item.Title</li>
                    </a>
                }
            </ul>
        </div>
        <div class="col-3">
            <ul type="none">
                @foreach (var item in Model.Skip(15).Take(5).ToList())
                {
                    <a href="@Url.Action(item.ActionName, item.ControllerName)">
                    <li>@item.Title</li>
                    </a>
                }
            </ul>
        </div>
    </div>
</div>

Restaurant_Management/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/CSS/bootstrap.min.css" rel="stylesheet" />
    @*<link href="~/CSS/dataTables.dataTables.min.css" rel="stylesheet" />*@
    <script src="~/JS/bootstrap.bundle.min.js"></script>
    @*<script src="~/JS/dataTables.min.js"></script>*@
    <script src="~/JS/jquery-3.7.1.min.js"></script>
    <link href="~/CSS/bootstrap-icons.min.css" rel="stylesheet" />

</head>
<body>
    @*@{ 
        Html.RenderAction("getNav", "Common");
    }*@

    <div class="container-fluid">
        @RenderBody()
    </div>
    
    @*@{ 
        Html.RenderAction("getFooter", "Common");
    }*@
</body>
</html>

Restaurant_Management/Views/Shared/_NavHeader.cshtml
@*@model IEnumerable<tblNavHeader>*@

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                @{
                    foreach (var item in Model)
                    {
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action(item.ActionName, item.ControllerName)">@item.Title</a>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("Create","User")">Create User</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("LoginUser","User")">Login</a>
                    </li>
                }
            </ul>

            @{
                string UID = User.Identity.Name;
                tblUser obj = null;
                using (var ctx = new Restaurant_ManagementEntities1())
                {
                    obj = ctx.tblUsers.Where(w => w.UserName == UID).FirstOrDefault();

                }

                <ul class="navbar-nav ms-auto">
                    <!-- Use ms-auto to align Username and Logout to the right -->
                    <li class="nav-item d-flex justify-content-center">
                        @if (obj != null)
                        {
                            <span class="navbar-text me-5 ">
                                <!-- Use me-3 for margin-right to space it from Logout -->
                                @obj.UserName
                            </span>
                        }
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("Logout", "User")">Logout</a>
                    </li>
                </ul>
            }
        </div>
    </div>
</nav>